version: '3'
services:
  app:
    container_name: coinbasecryptoservice
    build:
      context: .
      args:
      - ARCHIVE_NAME=coinbase-crypto-service-portal
      - APP_ENVIRONMENT=dev
    image: coinbasecryptoservice:latest
    depends_on:
    - db
    ports:
    - "8080:8080"
    environment:
    -  DB_HOST=db
    -  DB_PORT=5432
    -  DB_DATABASE=CoinbaseCrypto
    -  DB_USER=aathifSana
    -  DB_PASSWORD=aathifSana

  db:
    container_name: coinbasecryptodatabase
    image: 'postgres:10'
    environment:
    - POSTGRES_USER=aathifSana
    - POSTGRES_PASSWORD=aathifSana
    - POSTGRES_DB=CoinbaseCrypto
    ports:
    - "5432:5432"

