version: '3'
services:
  app:
    container_name: coinbasecryptoservice
    build:
      context: .
      args:
      - ARCHIVE_NAME=coinbase-crypto-service-portal
      - APP_ENVIRONMENT=dev
    image: coinbasecryptoservice:latest
    ports:
    - "8080:8080"
    environment:
    -  DB_HOST=database-1.cy4fxsq6wciy.us-west-2.rds.amazonaws.com
    -  DB_PORT=5432
    -  DB_DATABASE=CoinbaseCrypto
    -  DB_USER=aathifSana
    -  DB_PASSWORD=aathifSana


